Buoi3_ThucHanh/Ex3_1/Ex3_1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ex3_1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Buoi3_ThucHanh/Ex3_1/Ex3_1/Controllers/ThongTinSinhVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ex3_1.Controllers
{
    public class ThongTinSinhVienController : Controller
    {
        // GET: ThongTinSinhVien
        public ActionResult Index()
        {
            return View();
        }
    }
}

Buoi3_ThucHanh/Ex3_1/Ex3_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Hiển thị", "Index", "ThongTinSinhVien")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Buoi3_ThucHanh/Ex3_1/Ex3_1/Views/ThongTinSinhVien/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <table border="1" cellspacing="0">
        <tr>
            <th colspan="2">Thông tin sinh viên</th>
        </tr>
        <tr>
            <td>Mã SV:</td>
            <td>SV001</td>
        </tr>
        <tr>
            <td>Họ tên:</td>
            <td>Nguyễn Thị Vân</td>
        </tr>
        <tr>
            <td>Ngày sinh:</td>
            <td>16-09-2003</td>
        </tr>
        <tr>
            <td>Quê quán:</td>
            <td>Nam Từ Liêm, Hà Nội</td>
        </tr>
    </table>
</div>